{
  "format_version": 1,
  "sksl": {
    "entrypoint": "industrial_scan_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform float uTime;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / uSize;\n    float scanPos = mod(uTime * 0.5, 2.0) - 0.5;\n    float dist = abs((uv.x + uv.y) - scanPos);\n    float glow = smoothstep(0.1500000059604644775390625, 0.0, dist);\n    vec3 accentColor = vec3(0.0, 0.949999988079071044921875, 1.0);\n    vec3 finalColor = (accentColor * glow) * 0.300000011920928955078125;\n    fragColor = vec4(finalColor, (finalColor.x > 0.0) ? 0.300000011920928955078125 : 0.0);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uTime",
        "rows": 1,
        "type": 10
      }
    ]
  }
}