name: Deploy Pre-built Web to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Vercel Configuration
        run: |
          mkdir -p public/.vercel
          echo '{"projectId":"prj_z8UxqadECaYPhVV8T0bCkkUnHX0f","orgId":"team_lThvDLpDFA2AqSjN5SB0Egal","projectName":"portfolio-2026"}' > public/.vercel/project.json

      - name: Deploy to Vercel
        run: |
          npm install -g vercel@latest
          vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }} --yes --cwd public
